# -*- coding: utf-8 -*-
"""2026_ffff_IMDC_Forecast_Chikungunya_Cases_with_BPI_EW_Climate_data_HPC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ih5wWlOCuyGctJlEZaosDh6w6XBmbljN

## Level Structure for 2026 IMDC Submission

| Level `i` | Train Window | Forecast Window | Purpose |
|:---------:|:-------------|:----------------|:--------|
| 0  | EW01 2014 – EW26 2014 | EW40 2010 – EW39 2011 | Internal training level |
| 1  | EW01 2014 – EW26 2015 | EW40 2015 – EW39 2016 | Internal training level |
| 2  | EW01 2010 – EW26 2016 | EW40 2016 – EW39 2017 | Internal training level |
| 3  | EW01 2014 – EW26 2017 | EW40 2017 – EW39 2018 | Internal training level |
| 4  | EW01 2014 – EW26 2018 | EW40 2018 – EW39 2019 | Internal training level |
| 5  | EW01 2014 – EW26 2019 | EW40 2019 – EW39 2020 | Internal training level |
| 6 | EW01 2014 – EW26 2020 | EW40 2020 – EW39 2021 | Internal training level |
| 7 | EW01 2014 – EW26 2021 | EW40 2021 – EW39 2022 | Internal training level |
| 8 | EW01 2014 – EW25 2022 | EW41 2022 – EW40 2023 | ✅ Validation Test 1 |
| 9 | EW01 2014 – EW25 2023 | EW41 2023 – EW40 2024 | ✅ Validation Test 2 |
| 10 | EW01 2014 – EW25 2024 | EW41 2024 – EW40 2025 | ✅ Validation Test 3 |
| 11 | EW01 2014 – EW25 2025 | EW41 2025 – EW40 2026 | ✅ Validation Test 4 |
| 12 | EW01 2014 – EW25 2026 | EW41 2026 – EW40 2027 | 🎯 Final Forecast |

**Total levels:** `no_of_levels = 13` (indices i = 0 to 12)

## Start 2026 Sprint: 3rd Infodengue-Mosqlimate Dengue Challenge (IMDC)
This section presents the final CNN-LSTM ensemble using RMSE penalties, EW data,
and climate variables for the 2026 Sprint: 3rd Infodengue-Mosqlimate Dengue Challenge (IMDC).
Model: RJ_2026_IMDC_Hybrid_CNN_LSTM_MBB_BPI_EW_Climate
- Cell 1: Hierarchical expanding-window CNN-LSTM ensemble (17 levels, filters=[256,512], 100 epochs)
          Produces all_model_forecasts[i] and fake_X_pred_12..16 via residual chain.
- Cell 2: Moving Block Bootstrap Prediction Intervals (MBB-BPI)
          B=50 resamples × 2 filters = 100 bootstrap predictions per week.
          Point forecast: final_pred = 0.5 × all_model_forecasts[i] + 0.5 × boot_mean
          Intervals: empirical quantiles of bootstrap distribution recentered on final_pred,
          guaranteeing final_pred is always inside the intervals by construction.
- Cell 3: Save BPI CSVs for VT1 (2022-2023), VT2 (2023-2024), VT3 (2024-2025),
          VT4 (2025-2026, 53 weeks), Final Forecast (2026-2027).
          
 - Cell 4: save png files alomng with the prediction intervals ═══════════════════════════════════════════════════════════════════════════════
"""

# List of states to run the code
# states = ['SC', 'RS', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR',
#           'RJ', 'RN', 'RO', 'RR', 'MA', 'BA', 'CE', 'ES', 'GO', 'MG', 'AC', 'AL',
#           'SP', 'SE', 'AM', 'AP', 'TO', 'DF']

import sys
import os
import csv
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from math import sqrt
from sklearn.metrics import mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv1D, MaxPooling1D, Input, LSTM
from tensorflow.keras.optimizers import Adam

plt.rcParams['figure.figsize'] = (10, 5)
plt.style.use('fivethirtyeight')
tf.random.set_seed(123)
SEED = 1000

## 2026 model name by uf states with EW cases and climate data driven
model_name               = '2026_IMDC_Hybrid_CNN_LSTM_MBB_BPI_EW_Climate_Chikungunya'
selected_state_name      = sys.argv[1] if len(sys.argv) > 1 else 'AM'
# Change selected_state_name here for different uf's
# selected_state_name      = 'AM'

# Should show: 2026_processed_all_federal_units_dengue_data.csv
path                     = '/home/hkdas/infodengue2026/2026_processed_all_federal_units_chikungunya_data'
# Should show files named like: AM_climate_timeseries.csv, RJ_climate_timeseries.csv, SP_climate_timeseries.csv, etc. — one per state
climate_data_output_path = '/home/hkdas/infodengue2026/2026_processed_all_federal_units_climate_data'
forecast_dir_uf          = (f'/home/hkdas/infodengue2026'
                   f'/forecasts/chikungunya/{selected_state_name}')

# Create directories if they do not exist
if not os.path.exists(forecast_dir_uf):
    os.makedirs(forecast_dir_uf)

## Should show files named like: AM_climate_timeseries.csv, RJ_climate_timeseries.csv, SP_climate_timeseries.csv, etc. — one per state
file                     = '2026_processed_all_federal_units_chikungunya_data.csv'
df                       = pd.read_csv(os.path.join(path, file), low_memory=False)
no_of_levels             = 13   # was 16 → adds i=16 for Final Forecast 2026-2027
climate_uf_filename      = f"{selected_state_name}_climate_timeseries.csv"
df_climate_uf            = pd.read_csv(os.path.join(climate_data_output_path, climate_uf_filename), low_memory=False)
# Exclude 'date', 'epiweek', and 'geocode' columns
exclude_columns          = ['date','uf_code', 'uf']
climate_df = df_climate_uf.drop(columns=exclude_columns)
df_EW_data               = df[['epiweek', selected_state_name]]
dfm = pd.merge(df_EW_data, climate_df, on='epiweek', how='left')

# Penalty on the error
# L = 1
def training_splits(df, levels):
    splits = []
    for i in range(1, levels + 1):
        x_start = 201401
        x_end = 201400 + (26 + (i - 1) * 100)
        y_start = 201440 + (100 * (i - 1))
        y_end = y_start + 100

        x_split = df[df['epiweek'].between(x_start, x_end)].drop(columns=['epiweek'])
        y_split = df[df['epiweek'].between(y_start, y_end)].drop(columns=['epiweek'])

        splits.append((x_split, y_split))
    return splits

def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        X.append(sequence[i:i + n_steps, :])  # All features for n steps
        y.append(sequence[i + n_steps, 0])    # Predicting temp_min; change index if needed
    return np.array(X), np.array(y)

# Create splits for the defined levels
splits = training_splits(dfm, no_of_levels)

def compute_elementwise_average(arrays):
    # Convert the list of arrays into a 3D numpy array
    stacked_arrays = np.stack(arrays, axis=0)

    # Compute the mean across the new dimension (axis=0)
    average_array = np.mean(stacked_arrays, axis=0)

    return average_array

# this padding helps us to adjust the data if there is any dimension mismatch issue, for example when i=5 dim = 52, in other case 52
def pad_arrays(arrays, target_shape):
    padded_arrays = [np.pad(array, [(0, target_shape[k] - array.shape[k]) for k in range(len(target_shape))], mode='constant') for array in arrays]
    return padded_arrays


def calculate_weights(rmse_scores):
    penalties = 1 / np.array(rmse_scores)
    total_penalty = np.sum(penalties)
    weights = penalties / total_penalty
    return weights

# def ensemble_predictions(prediction_vectors, weights):
#     prediction_vectors = np.array(prediction_vectors)
#     weighted_sum = np.sum(prediction_vectors * weights[:, np.newaxis], axis=0)
#     return weighted_sum

def ensemble_predictions(prediction_vectors, weights):
    """
    Compute the weighted average of prediction vectors from different models.

    Parameters:
    prediction_vectors (list of np.array): List of prediction vectors from different models.
    weights (np.array): Weights for each model.

    Returns:
    np.array: Final ensemble prediction vector.
    """
    # Convert list of prediction vectors to a numpy array with shape (num_models, num_samples, 1)
    prediction_vectors = np.array(prediction_vectors)

    # Ensure weights is a 1D array with shape (num_models,)
    weights = np.array(weights)

    # Reshape weights to (num_models, 1, 1) to align with prediction_vectors shape (num_models, num_samples, 1)
    weights = weights[:, np.newaxis, np.newaxis]

    # Compute the weighted sum
    weighted_sum = np.sum(prediction_vectors * weights, axis=0)

    return weighted_sum

# Initialize lists to store forecasts and training data
all_model_forecasts              = []
all_X_trains                     = []
all_y_trains                     = []
all_prev_level_X_pred            = []
all_prev_level_true_data         = []
all_model_r2_score               = []
all_model_forecasting_r2_score   = []
all_boot_intervals_per_level     = []   # BPI intervals per level


# Function to define and compile CNN-LSTM model
def build_cnn_lstm_model(filters, kernel_size, learning_rate, n_steps, n_features):
    tf.keras.backend.clear_session()  # ← add this line
    model = Sequential()
    model.add(Conv1D(filters=filters, kernel_size=kernel_size, activation='relu', input_shape=(n_steps, n_features)))
    model.add(Conv1D(filters=filters//2, kernel_size=kernel_size, activation='relu'))
    model.add(MaxPooling1D(pool_size=1))
    model.add(LSTM(50, activation='relu'))
    model.add(Dense(30))
    model.add(Dense(10))
    model.add(Dense(1))
    opt = Adam(learning_rate=learning_rate)
    model.compile(optimizer=opt, loss='mse', metrics=['accuracy'])
    return model


fig, ax = plt.subplots(len(splits), 1, figsize=(20, 60))

if len(splits) == 1:
    ax = [ax]

# Initialize a variable to store residuals from the previous level
# Parameters
previous_residuals = np.zeros(25)
mse_scores         = []
n_steps            = 1
n_features         = 16
filters_vec        = [256, 512]   # ensemble filters — BPI uses same list in Cell 2

# Preparing training, testing, and prediction data for different levels i

for i, (train, val) in enumerate(splits):
    #X_train_raw = train.to_numpy() #train[climate_features].to_numpy()
    train_new_data = train.to_numpy() # val[climate_features].to_numpy()
    val_new_data = val.to_numpy()
    # X_train, y_train = split_sequence(X_train_raw, y_train_raw, n_steps)
    # X_val, y_val = split_sequence(X_val_raw, y_val_raw, n_steps)
    # X_train.shape = (n_samples, n_steps, n_features)
    X, y = split_sequence(train_new_data, n_steps)

    print("Shape before reshaping:", X.shape)
    y_start = 201441 + (100 * (i))
    y_end = y_start + 99
    print(f"Fold {i}:")
    print("X_train shape:", X.shape)
    print("y_train shape:", y.shape)

    ######################## new ##############
    # Handle residual logic which is working for i= 0, residual is the last column
    if i == 0:
        # For level 0, use zeros as second feature
        X_seq = X
        y_seq = y
        zero_column = np.zeros((X_seq.shape[0], 1))
        # Take last timestep's features only (shape: (samples, features))
        X_last_step = X_seq[:, -1, :]
        X = np.concatenate((X_last_step, zero_column), axis=1)
    else:
        # Get previous residuals up to the length of current X
        X_seq = X
        y_seq = y
        residual_column = previous_residuals[:X_seq.shape[0]].reshape(-1, 1)
        X_last_step = X_seq[:, -1, :]
        X = np.concatenate((X_last_step, residual_column), axis=1)

    print('Display i and X after after adding the residuals')
    print(i)
    print("Shape after reshaping:", X.shape)
    y_start = 201441 + (100 * (i))
    y_end = y_start + 99
    print(f"Fold {i}:")
    print("X_train shape:", X.shape)
    print("y_train shape:", y.shape)
    print(X)

    ######################## new ##############
    #n_features = X.shape[1]                                                                         # Adjusted to handle multiple features
    print(f'Level {i} | X shape after residual: {X.shape}')
    #num_output_features = 1
    X_train = X
    y_train = y

    print(f"\nLevel {i}")
    print("X_train shape:", X_train.shape)
    print("y_train shape:", y_train.shape)

    # ── X_test / y_test per level ──────────────────────────────────────
    if 0 <= i < 8:
        #X_test, y_test = split_sequence(val_new_data, n_steps)
        X_test_seq, y_test = split_sequence(val_new_data, n_steps)  # shape: (samples, n_steps, features)
        X_test_last_step = X_test_seq[:, -1, :]  # Take last timestep features
        if i == 0:
          # For level 0, append a zero column
          X_test_residual_feature = np.zeros((X_test_seq.shape[0], 1))
        else:
          # For level > 0, append residuals from previous training prediction
          X_test_residual_feature = previous_residuals[:X_test_seq.shape[0]].reshape(-1, 1)

        # Concatenate last step features with residual column
        X_test = np.concatenate((X_test_last_step, X_test_residual_feature), axis=1)
        # X_test_zero_feature = np.zeros((X_test.shape[0], 1))
        # X_test = np.concatenate((X_test, X_test_zero_feature), axis=1)

    # elif i == 8:
    #     # calculate fake_X_pred
    #     average = []
    #     # Determine the target shape (e.g., max shape among arrays)
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_X_pred[:i]) for l in range(len(all_prev_level_X_pred[0].shape)))

    #     # Pad arrays and compute average
    #     padded_arrays = pad_arrays(all_prev_level_X_pred[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     if len(average) == 53:
    #       average = average[:-1]
    #     else:
    #       average  = average
    #     fake_X_pred_12 = average
    #     X_test =  fake_X_pred_12

    #     # calculate fake_true_data
    #     average = []
    #     # Determine the target shape (e.g., max shape among arrays)
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_true_data[:i]) for l in range(len(all_prev_level_true_data[0].shape)))

    #     # Pad arrays and compute average
    #     padded_arrays = pad_arrays(all_prev_level_true_data[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     if len(average) == 53:
    #       average = average[:-1]
    #     else:
    #       average  = average
    #     fake_true_data_12 = average
    #     y_test = fake_true_data_12

    # elif i == 9:
    #     # calculate fake_X_pred
    #     average = []
    #     # Determine the target shape (e.g., max shape among arrays)
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_X_pred[:i]) for l in range(len(all_prev_level_X_pred[0].shape)))

    #     # Pad arrays and compute average
    #     padded_arrays = pad_arrays(all_prev_level_X_pred[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     if len(average) == 53:
    #       average = average[:-1]
    #     else:
    #       average  = average

    #     fake_X_pred_13 = average
    #     X_test =  fake_X_pred_13

    #     # calculate fake_true_data
    #     average = []
    #     # Determine the target shape (e.g., max shape among arrays)
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_true_data[:i]) for l in range(len(all_prev_level_true_data[0].shape)))

    #     # Pad arrays and compute average
    #     padded_arrays = pad_arrays(all_prev_level_true_data[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     if len(average) == 53:
    #       average = average[:-1]
    #     else:
    #       average  = average
    #     fake_true_data_13 = average
    #     y_test = fake_true_data_13

    # elif i == 10:
    #     # calculate fake_X_pred
    #     average = []
    #     # Determine the target shape (e.g., max shape among arrays)
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_X_pred[:i]) for l in range(len(all_prev_level_X_pred[0].shape)))

    #     # Pad arrays and compute average
    #     padded_arrays = pad_arrays(all_prev_level_X_pred[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     if len(average) == 53:
    #       average = average[:-1]
    #     else:
    #       average  = average

    #     fake_X_pred_14 = average
    #     X_test =  fake_X_pred_14

    #     # calculate fake_true_data
    #     average = []
    #     # Determine the target shape (e.g., max shape among arrays)
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_true_data[:i]) for l in range(len(all_prev_level_true_data[0].shape)))

    #     # Pad arrays and compute average
    #     padded_arrays = pad_arrays(all_prev_level_true_data[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     if len(average) == 53:
    #       average = average[:-1]
    #     else:
    #       average  = average
    #     fake_true_data_14 = average
    #     y_test = fake_true_data_14

    # elif i == 11:
    #     average = []
    #     # Validation Test 4: EW41 2025 – EW40 2026 needs 53 weeks so do NOT trim
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_X_pred[:i])
    #                          for l in range(len(all_prev_level_X_pred[0].shape)))
    #     padded_arrays = pad_arrays(all_prev_level_X_pred[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     # fake_X_pred_15 = average[:-1] if len(average) == 53 else average
    #     fake_X_pred_15 = average  # ← keep all rows, do NOT trim
    #     X_test = fake_X_pred_15

    #     # calculate fake_true_data
    #     average = []
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_true_data[:i])
    #                          for l in range(len(all_prev_level_true_data[0].shape)))
    #     padded_arrays = pad_arrays(all_prev_level_true_data[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     #fake_true_data_15 = average[:-1] if len(average) == 53 else average
    #     fake_true_data_15 = average  # ← REMOVE the [:-1] trimming, keep all rows
    #     y_test = fake_true_data_15

    # # forecast for EW 41 2025 - EW 40 2026
    # else: # i == 12: Final Forecast EW41 2026 – EW40 2027
    #     # calculate fake_X_pred
    #     average = []
    #     # Determine the target shape (e.g., max shape among arrays)
    #     target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_X_pred[:i]) for l in range(len(all_prev_level_X_pred[0].shape)))

    #     # Pad arrays and compute average
    #     padded_arrays = pad_arrays(all_prev_level_X_pred[:i], target_shape)
    #     average = compute_elementwise_average(padded_arrays)
    #     if len(average) == 53:
    #       average = average[:-1]
    #     else:
    #       average  = average

    #     fake_X_pred_16 = average
    #     X_test =  fake_X_pred_16

    elif i == 8:  # VT1: available up to EW25 2022, forecast EW40 2022–EW39 2023
        feature_cols = [c for c in dfm.columns if c != 'epiweek']
        target_ews   = list(range(202240, 202253)) + list(range(202301, 202340))
        clim_rows    = []
        for ew in target_ews:
            ew_only = ew % 100
            mask    = (dfm['epiweek'].apply(lambda x: x % 100) == ew_only) & (dfm['epiweek'] < 202226)
            clim_rows.append(dfm.loc[mask, feature_cols].mean().values)
        raw            = np.array(clim_rows)
        res_col        = np.zeros((len(raw), 1))
        fake_X_pred_12 = np.concatenate([raw, res_col], axis=1)[:, np.newaxis, :]
        for l in range(len(fake_X_pred_12) - 1):
            fake_X_pred_12[l+1, 0, 15] = previous_residuals[l] if l < len(previous_residuals) else 0.0
        X_test = fake_X_pred_12
        fake_true_data_12 = dfm[dfm['epiweek'].between(202241, 202340)][selected_state_name].values
        y_test = fake_true_data_12

    elif i == 9:  # VT2: available up to EW25 2023
        feature_cols = [c for c in dfm.columns if c != 'epiweek']
        target_ews   = list(range(202340, 202353)) + list(range(202401, 202440))
        clim_rows    = []
        for ew in target_ews:
            ew_only = ew % 100
            mask    = (dfm['epiweek'].apply(lambda x: x % 100) == ew_only) & (dfm['epiweek'] < 202326)
            clim_rows.append(dfm.loc[mask, feature_cols].mean().values)
        raw            = np.array(clim_rows)
        res_col        = np.zeros((len(raw), 1))
        fake_X_pred_13 = np.concatenate([raw, res_col], axis=1)[:, np.newaxis, :]
        for l in range(len(fake_X_pred_13) - 1):
            fake_X_pred_13[l+1, 0, 15] = previous_residuals[l] if l < len(previous_residuals) else 0.0
        X_test = fake_X_pred_13
        fake_true_data_13 = dfm[dfm['epiweek'].between(202341, 202440)][selected_state_name].values
        y_test = fake_true_data_13

    elif i == 10:  # VT3: available up to EW25 2024
        feature_cols = [c for c in dfm.columns if c != 'epiweek']
        target_ews   = list(range(202440, 202453)) + list(range(202501, 202540))
        clim_rows    = []
        for ew in target_ews:
            ew_only = ew % 100
            mask    = (dfm['epiweek'].apply(lambda x: x % 100) == ew_only) & (dfm['epiweek'] < 202426)
            clim_rows.append(dfm.loc[mask, feature_cols].mean().values)
        raw            = np.array(clim_rows)
        res_col        = np.zeros((len(raw), 1))
        fake_X_pred_14 = np.concatenate([raw, res_col], axis=1)[:, np.newaxis, :]
        for l in range(len(fake_X_pred_14) - 1):
            fake_X_pred_14[l+1, 0, 15] = previous_residuals[l] if l < len(previous_residuals) else 0.0
        X_test = fake_X_pred_14
        fake_true_data_14 = dfm[dfm['epiweek'].between(202441, 202540)][selected_state_name].values
        y_test = fake_true_data_14

    elif i == 11: # VT4: available up to EW25 2025
        feature_cols = [c for c in dfm.columns if c != 'epiweek']
        target_ews   = list(range(202540, 202553)) + list(range(202601, 202641))
        clim_rows    = []
        for ew in target_ews:
            ew_only = ew % 100
            mask    = (dfm['epiweek'].apply(lambda x: x % 100) == ew_only) & (dfm['epiweek'] < 202526)
            clim_rows.append(dfm.loc[mask, feature_cols].mean().values)
        raw            = np.array(clim_rows)
        res_col        = np.zeros((len(raw), 1))
        fake_X_pred_15 = np.concatenate([raw, res_col], axis=1)[:, np.newaxis, :]
        for l in range(len(fake_X_pred_15) - 1):
            fake_X_pred_15[l+1, 0, 15] = previous_residuals[l] if l < len(previous_residuals) else 0.0
        X_test = fake_X_pred_15
        real_vals         = dfm[dfm['epiweek'].between(202541, 202640)][selected_state_name].values
        fake_true_data_15 = np.pad(real_vals, (0, 53 - len(real_vals)))  # pad to 53 with zeros because we have limited real data in this step
        y_test            = fake_true_data_15

    else:  # i == 12: Final Forecast, available up to EW25 2026
        feature_cols = [c for c in dfm.columns if c != 'epiweek']
        target_ews   = list(range(202641, 202653)) + list(range(202701, 202741))
        clim_rows    = []
        for ew in target_ews:
            ew_only = ew % 100
            mask    = (dfm['epiweek'].apply(lambda x: x % 100) == ew_only) & (dfm['epiweek'] < 202626)
            clim_rows.append(dfm.loc[mask, feature_cols].mean().values)
        raw            = np.array(clim_rows)
        res_col        = np.zeros((len(raw), 1))
        fake_X_pred_16 = np.concatenate([raw, res_col], axis=1)[:, np.newaxis, :]
        for l in range(len(fake_X_pred_16) - 1):
            fake_X_pred_16[l+1, 0, 15] = previous_residuals[l] if l < len(previous_residuals) else 0.0
        X_test = fake_X_pred_16
        fake_true_data_16 = np.zeros(len(target_ews))
        y_test = fake_true_data_16

        # calculate fake_true_data
        average = []
        # Determine the target shape (e.g., max shape among arrays)
        target_shape = tuple(max(arr.shape[l] for arr in all_prev_level_true_data[:i]) for l in range(len(all_prev_level_true_data[0].shape)))

        # Pad arrays and compute average
        padded_arrays = pad_arrays(all_prev_level_true_data[:i], target_shape)
        average = compute_elementwise_average(padded_arrays)
        if len(average) == 53:
          average = average[:-1]
        else:
          average  = average
        fake_true_data_16 = average
        y_test = fake_true_data_16

   # Ensure X_train and X_test have the correct shape
    X_train = X_train.reshape((X_train.shape[0], n_steps, n_features))
    X_test = X_test.reshape((X_test.shape[0], n_steps, n_features))

    # Ensemble predictions
    ensemble_predictions_vec   = []
    ensemble_rmse_scores_vec   = []
    for j in range(len(filters_vec)):
        filters     = filters_vec[j]
        kernel_size = 1
        learning_rate = 0.0001
        # Build and train the model
        model = build_cnn_lstm_model(filters, kernel_size, learning_rate, n_steps, n_features)
        model.fit(X_train, y_train, epochs=100, validation_split=0.1, batch_size=5, verbose=0)

        # Make predictions and store
        yhat = model.predict(X_test, verbose=0)
        ensemble_predictions_vec.append(yhat)
        # if len(yhat)== 52:
        #   yhat = yhat
        # else:
        #   yhat = yhat[:-1]
        # if len(y_test)== 52:
        #   y_test = y_test
        # else:
        #   y_test = y_test[:-1]

        # REPLACE:
        n_weeks = 53 if i == 11 else 52
        yhat    = yhat[:n_weeks]
        y_test  = y_test[:n_weeks]

        new_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, yhat))
        ensemble_rmse_scores_vec.append(new_ensemble_rmse_scores)

    # Average ensemble predictions
    # mean_ensemble_predictions = np.mean(ensemble_predictions_vec, axis=0)
    # ensemble_predictions_vec.append(mean_ensemble_predictions)
    # if len(mean_ensemble_predictions)==52:
    #   mean_ensemble_predictions = mean_ensemble_predictions
    # else:
    #   mean_ensemble_predictions = mean_ensemble_predictions[:-1]
    # new_mean_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, mean_ensemble_predictions))

    # Average ensemble predictions
    mean_ensemble_predictions = np.mean(ensemble_predictions_vec, axis=0)
    ensemble_predictions_vec.append(mean_ensemble_predictions)
    n_weeks = 53 if i == 11 else 52
    mean_ensemble_predictions = mean_ensemble_predictions[:n_weeks]
    new_mean_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, mean_ensemble_predictions))

    ensemble_rmse_scores_vec.append(new_mean_ensemble_rmse_scores)
    ensemble_weights     = calculate_weights(ensemble_rmse_scores_vec)
    new_ensemble_predictions = ensemble_predictions(ensemble_predictions_vec, ensemble_weights)


    # # Evaluate the best model
    y_test_regular = y_test

    yhat_regular       = new_ensemble_predictions
    if len(y_test_regular) == len(yhat_regular):
      print('Best Test RMSE:', sqrt(mean_squared_error(y_test_regular, yhat_regular)))
      print('Best Test R2 Score:', r2_score(y_test_regular, yhat_regular))
      colect_r2_score = r2_score(y_test_regular, yhat_regular)
    else:
      yhat_regular = yhat_regular[:-1]
      print('Best Test RMSE:', sqrt(mean_squared_error(y_test_regular, yhat_regular)))
      print('Best Test R2 Score:', r2_score(y_test_regular, yhat_regular))
      colect_r2_score = r2_score(y_test_regular, yhat_regular)

    all_model_r2_score.append(colect_r2_score)

    # ── pred_epiweeks / true_data / X_pred per level ───────────────────

    if 0<=i <8:
      pred_epiweeks = dfm[dfm['epiweek'].between(y_start, y_end)]['epiweek']
      true_data = dfm[dfm['epiweek'].between(y_start, y_end)][selected_state_name]
      X_pred         = X_test

    # should we chose the true data . Actualy no by assuming that we can not use the true data
    elif i==8:
      pred_epiweeks  =  list(range(202241, 202253)) + list(range(202301, 202341))
      true_data      = fake_true_data_12
      #X_pred         = X_test      # this is the actual in main code
      X_pred        = fake_X_pred_12   # we need to check here
    elif i==9:
      pred_epiweeks  =  list(range(202341, 202353)) + list(range(202401, 202441))
      true_data      = fake_true_data_13
      #X_pred         = X_test      # this is the actual in main code
      X_pred        = fake_X_pred_13   # we need to check here
    elif i==10:
      pred_epiweeks  =  list(range(202441, 202453)) + list(range(202501, 202541))
      true_data      = fake_true_data_14
      #X_pred         = X_test      # this is the actual in main code
      X_pred        = fake_X_pred_14   # we need to check here

    elif i == 11:
        pred_epiweeks = list(range(202541, 202553)) + list(range(202601, 202642)) # pred_epiweeks = 53 to match model_forecast = 53 and td_plot = 53.
        true_data     = fake_true_data_15
        X_pred        = fake_X_pred_15

    else:  # i == 12
        pred_epiweeks = list(range(202641, 202653)) + list(range(202701, 202741))
        true_data     = fake_true_data_16
        X_pred        = fake_X_pred_16

  #   # ============================================================
  #   # Branch A: i < 12 — real validation data available
  #   # ============================================================

    if 0<=i<8:
      print(f'true_data len {len(true_data)}  with i : {i}')
      print(true_data.values)
      print(f'X_pred len {len(true_data)}  with i : {i}')
      print(X_pred)

      # New Ensemble predictions
      ensemble_predictions_vec   = []
      ensemble_rmse_scores_vec   = []
      #for j in range(ensemble_size):
      for j in range(len(filters_vec)):
          filters     = filters_vec[j]
          kernel_size = 1  # Ensure kernel_size <= n_steps
          learning_rate = 0.0001
          # Build and train the model
          model = build_cnn_lstm_model(filters, kernel_size, learning_rate, n_steps, n_features)
          model.fit(X_train, y_train, epochs=100, validation_split=0.1, batch_size=5, verbose=0)

          # Make predictions and store
          yhat = model.predict(X_test, verbose=0)
          ensemble_predictions_vec.append(yhat)
          # new line using ensemble
          #new_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, ensemble_predictions))

          # if len(yhat)== 52:
          #   yhat = yhat
          # else:
          #   yhat = yhat[:-1]
          # if len(y_test)== 52:
          #   y_test = y_test
          # else:
          #   y_test = y_test[:-1]

          # REPLACE:
          n_weeks = 53 if i == 11 else 52
          yhat    = yhat[:n_weeks]
          y_test  = y_test[:n_weeks]
          new_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, yhat))
          ensemble_rmse_scores_vec.append(new_ensemble_rmse_scores)

      # # Average ensemble predictions
      # mean_ensemble_predictions = np.mean(ensemble_predictions_vec, axis=0)
      # ensemble_predictions_vec.append(mean_ensemble_predictions)
      # if len(mean_ensemble_predictions)== 52:
      #  mean_ensemble_predictions = mean_ensemble_predictions
      # else:
      #  mean_ensemble_predictions = mean_ensemble_predictions[:-1]
      # if len(y_test)== 52:
      #  y_test = y_test
      # else:
      #  y_test = y_test[:-1]
      # new_mean_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, mean_ensemble_predictions))

      # Average ensemble predictions
      mean_ensemble_predictions = np.mean(ensemble_predictions_vec, axis=0)
      ensemble_predictions_vec.append(mean_ensemble_predictions)
      n_weeks = 53 if i == 11 else 52
      mean_ensemble_predictions = mean_ensemble_predictions[:n_weeks]
      new_mean_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, mean_ensemble_predictions))

      ensemble_rmse_scores_vec.append(new_mean_ensemble_rmse_scores)
      ensemble_weights     = calculate_weights(ensemble_rmse_scores_vec)
      new_ensemble_predictions = ensemble_predictions(ensemble_predictions_vec, ensemble_weights)
      model_forecast       = new_ensemble_predictions

      print(f'model_forecast len {len(model_forecast)}   with i : {i}')
      print(model_forecast)

      # if len(true_data)==52:
      #   true_data = true_data
      # else:
      #   true_data = true_data[:-1]
      # if len(model_forecast)==52:
      #   model_forecast = model_forecast
      # else:
      #   model_forecast = model_forecast[:-1]

      tv = true_data.values if hasattr(true_data, 'values') else np.array(true_data)
      mf = model_forecast.squeeze()
      n_c = min(len(tv), len(mf))
      tv = tv[:n_c]
      mf = mf[:n_c]
      difference = tv - mf
      residuals = difference
      model_forecast = mf.reshape(-1, 1)
      true_data = tv
      difference = true_data  - model_forecast.squeeze()    # model_forecast.squeeze() males an array as we true_data.values - model_forecast
      residuals = difference
      print(f'residuals for {i} of {len(residuals)}')
      print(residuals)
      print(f'X_pred for {i} of {len(X_pred)}')
      print(X_pred)


    ## ── X_pred residual update ─────────────────────────────────────────

    if 0<=i<8:
      X_pred         = X_test
      # Ensure that the shape of residuals matches the second column of X_pred
      if len(X_pred) !=52:
        for l in range(len(X_pred)-1):
            print(f'len(X_pred) is {len(X_pred)} for {i}')
            # X_pred[l+1, :, 1] = residuals[l]  # ← puts residual into temperature column
            X_pred[l+1, 0, 15] = residuals[l]   # ← puts residual into the correct slot
      else:
        for l in range(len(X_pred)-1):
            # X_pred[l+1, :, 1] = residuals[l]  # ← puts residual into temperature column
            X_pred[l+1, 0, 15] = residuals[l]   # ← puts residual into the correct slot
      # Print the modified X_pred to verify
      print(f'Print the modified X_pred to verify for {i} of {len(X_pred)}')
      print(X_pred)


      # New Ensemble predictions
      ensemble_predictions_vec   = []
      ensemble_rmse_scores_vec   = []
      for j in range(len(filters_vec)):
          filters     = filters_vec[j]
          kernel_size = 1  # Ensure kernel_size <= n_steps
          learning_rate = 0.0001
          # Build and train the model
          model = build_cnn_lstm_model(filters, kernel_size, learning_rate, n_steps, n_features)
          model.fit(X_train, y_train, epochs=100, validation_split=0.1, batch_size=5, verbose=0)

          # Make predictions and store
          yhat = model.predict(X_test, verbose=0)
          ensemble_predictions_vec.append(yhat)
          # new line using ensemble

          # if len(yhat)== 52:
          #   yhat = yhat
          # else:
          #   yhat = yhat[:-1]
          # if len(y_test)== 52:
          #   y_test = y_test
          # else:
          #   y_test = y_test[:-1]

          # REPLACE:
          n_weeks = 53 if i == 11 else 52
          yhat    = yhat[:n_weeks]
          y_test  = y_test[:n_weeks]
          new_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, yhat))
          ensemble_rmse_scores_vec.append(new_ensemble_rmse_scores)

      # Average ensemble predictions
      mean_ensemble_predictions = np.mean(ensemble_predictions_vec, axis=0)
      ensemble_predictions_vec.append(mean_ensemble_predictions)
      n_weeks = 53 if i == 11 else 52
      mean_ensemble_predictions = mean_ensemble_predictions[:n_weeks]
      new_mean_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, mean_ensemble_predictions))

      ensemble_rmse_scores_vec.append(new_mean_ensemble_rmse_scores)
      ensemble_weights     = calculate_weights(ensemble_rmse_scores_vec)
      new_ensemble_predictions = ensemble_predictions(ensemble_predictions_vec, ensemble_weights)

      model_forecast       = new_ensemble_predictions

      print(f'new model_forecast len {len(model_forecast)}   with residual in X_pred i : {i}')
      print(model_forecast)
      print(f'residuals for {i} of {len(residuals)}')
      print(residuals)
      print(f'X_train {i} of {len(X_train)}')
      print(X_train)

      # Add model_forecast to list
      all_prev_level_X_pred.append(X_pred)
      # print(f'length of all_prev_level_X_pred data {len(all_prev_level_X_pred)} for {i}')
      # print(all_prev_level_X_pred)
      all_prev_level_true_data.append(true_data)

    else:
      if i==8:
        forecasting_y_start = 202241
        forecasting_y_end   = 202340
        forecasting_true_data_level_12 = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)][selected_state_name]
        all_prev_level_true_data.append(forecasting_true_data_level_12)

        pred_X_start = 202240
        pred_X_end   = 202339
        feature_cols = [c for c in dfm.columns if c != 'epiweek']          # 15 cols: AM + 14 climate
        raw          = dfm[dfm['epiweek'].between(pred_X_start, pred_X_end)][feature_cols].values  # (N, 15)
        residual_col = np.zeros((len(raw), 1))                              # residual slot initialised to 0
        full_feat    = np.concatenate([raw, residual_col], axis=1)          # (N, 16)
        formatted_data = full_feat[:, np.newaxis, :]                        # (N, 1, 16)
        for l in range(len(formatted_data) - 1):
          formatted_data[l+1, 0, 15] = residuals[l]                        # inject residual into col 15
        real_X_pred_at_level_12 = formatted_data[:]
        all_prev_level_X_pred.append(real_X_pred_at_level_12)

      elif i==9:
        forecasting_y_start = 202341
        forecasting_y_end   = 202440
        forecasting_true_data_level_13 = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)][selected_state_name]
        all_prev_level_true_data.append(forecasting_true_data_level_13)

        pred_X_start = 202340
        pred_X_end   = 202439
        feature_cols = [c for c in dfm.columns if c != 'epiweek']          # 15 cols: AM + 14 climate
        raw          = dfm[dfm['epiweek'].between(pred_X_start, pred_X_end)][feature_cols].values  # (N, 15)
        residual_col = np.zeros((len(raw), 1))
        full_feat    = np.concatenate([raw, residual_col], axis=1)          # (N, 16)
        formatted_data = full_feat[:, np.newaxis, :]                        # (N, 1, 16)
        for l in range(len(formatted_data) - 1):
          formatted_data[l+1, 0, 15] = residuals[l]
        real_X_pred_at_level_13 = formatted_data[:]
        all_prev_level_X_pred.append(real_X_pred_at_level_13)

      elif i==10:
        forecasting_y_start = 202441
        forecasting_y_end   = 202540
        forecasting_true_data_level_14 = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)][selected_state_name]
        all_prev_level_true_data.append(forecasting_true_data_level_14)

        pred_X_start = 202440
        pred_X_end   = 202539
        feature_cols = [c for c in dfm.columns if c != 'epiweek']          # 15 cols: AM + 14 climate
        raw          = dfm[dfm['epiweek'].between(pred_X_start, pred_X_end)][feature_cols].values  # (N, 15)
        residual_col = np.zeros((len(raw), 1))
        full_feat    = np.concatenate([raw, residual_col], axis=1)          # (N, 16)
        formatted_data = full_feat[:, np.newaxis, :]                        # (N, 1, 16)
        for l in range(len(formatted_data) - 1):
          formatted_data[l+1, 0, 15] = residuals[l]
        real_X_pred_at_level_14 = formatted_data[:]
        all_prev_level_X_pred.append(real_X_pred_at_level_14)

      elif i == 11:
        forecasting_y_start = 202541
        forecasting_y_end   = 202640
        forecasting_true_data_level_15 = dfm[dfm['epiweek'].between(
            forecasting_y_start, forecasting_y_end)][selected_state_name]
        all_prev_level_true_data.append(forecasting_true_data_level_15)

        pred_X_start = 202540
        pred_X_end   = 202639
        feature_cols = [c for c in dfm.columns if c != 'epiweek']          # 15 cols: AM + 14 climate
        raw          = dfm[dfm['epiweek'].between(pred_X_start, pred_X_end)][feature_cols].values  # (N, 15)
        residual_col = np.zeros((len(raw), 1))
        full_feat    = np.concatenate([raw, residual_col], axis=1)          # (N, 16)
        formatted_data = full_feat[:, np.newaxis, :]                        # (N, 1, 16)
        for l in range(len(formatted_data) - 1):
            formatted_data[l+1, 0, 15] = residuals[l]
        all_prev_level_X_pred.append(formatted_data[:])


      else:  # i == 12 — Final Forecast EW41 2026 – EW40 2027
        # No observed future climate exists in dfm for 2026-2027.
        # Use climatological mean: average of the same epiweeks across all prior years.
        feature_cols  = [c for c in dfm.columns if c != 'epiweek']         # 15 cols: AM + 14 climate

        # Target epiweek sequence for 2026-2027: EW41→EW52 2026 then EW01→EW40 2027
        target_ews = list(range(202641, 202653)) + list(range(202701, 202741))  # 52 epiweeks

        clim_rows = []
        for ew in target_ews:
            ew_only = ew % 100                                              # strip year, keep week number
            # gather all prior years' rows for this epiweek number
            mask  = dfm['epiweek'].apply(lambda x: x % 100) == ew_only
            prior = dfm.loc[mask, feature_cols]
            clim_rows.append(prior.mean().values)                           # climatological mean row
        clim_array  = np.array(clim_rows)                                  # (52, 15)
        residual_col = np.zeros((len(clim_array), 1))
        full_feat    = np.concatenate([clim_array, residual_col], axis=1)  # (52, 16)
        formatted_data = full_feat[:, np.newaxis, :]                       # (52, 1, 16)
        for l in range(len(formatted_data) - 1):
            formatted_data[l+1, 0, 15] = residuals[l]
        X_pred = formatted_data

      # Print the modified X_pred to verify
      print(X_pred)
      all_prev_level_X_pred.append(X_pred)                                      # still we are colecting for the next level
      print(f'length of all_prev_level_X_pred data {len(all_prev_level_X_pred)} for {i}')
      print(all_prev_level_X_pred)

      # New Ensemble predictions

      ensemble_predictions_vec   = []
      ensemble_rmse_scores_vec   = []

      # Loop through ensemble models for the number of ensemble_size
      for j in range(len(filters_vec)):
          filters     = filters_vec[j]
          kernel_size = 1  # Ensure kernel_size <= n_steps
          learning_rate = 0.0001
          # Build and train the model
          model = build_cnn_lstm_model(filters, kernel_size, learning_rate, n_steps, n_features)
          model.fit(X_train, y_train, epochs=100, validation_split=0.1, batch_size=5, verbose=0)

          # Step 6: Update the inner ensemble X_test condition — change 0<=i<15 to 0<=i<16:

          if 0<=i<12:
            X_test = X_pred  # fake_X_pred
          else:
            X_test = fake_X_pred_16

          # Make predictions and store
          yhat = model.predict(X_test, verbose=0)
          ensemble_predictions_vec.append(yhat)

          # if len(yhat)== 52:
          #   yhat = yhat
          # else:
          #   yhat = yhat[:-1]
          # if len(y_test)== 52:
          #   y_test = y_test
          # else:
          #   y_test = y_test[:-1]

          # REPLACE:
          n_weeks = 53 if i == 11 else 52
          yhat    = yhat[:n_weeks]
          y_test  = y_test[:n_weeks]
          # new line using ensemble
          #new_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, ensemble_predictions))
          new_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, yhat))
          ensemble_rmse_scores_vec.append(new_ensemble_rmse_scores)
      # ← ADD THESE 8 LINES (6 spaces indent, same as the for loop above):
      mean_ensemble_predictions = np.mean(ensemble_predictions_vec, axis=0)
      ensemble_predictions_vec.append(mean_ensemble_predictions)
      n_weeks = 53 if i == 11 else 52
      mean_ensemble_predictions = mean_ensemble_predictions[:n_weeks]
      new_mean_ensemble_rmse_scores = sqrt(mean_squared_error(y_test, mean_ensemble_predictions))
      ensemble_rmse_scores_vec.append(new_mean_ensemble_rmse_scores)
      ensemble_weights = calculate_weights(ensemble_rmse_scores_vec)
      model_forecast = ensemble_predictions(ensemble_predictions_vec, ensemble_weights)

    # Add model_forecast to list
    all_model_forecasts.append(model_forecast)
    # forecasting_r_2_score = r2_score(true_data, model_forecast)
    # all_model_forecasting_r2_score.append(forecasting_r_2_score)

    # Store X_train for current level
    all_X_trains.append(X_train.reshape(X_train.shape[0], -1))  # Flatten for saving
    all_y_trains.append(y_train)

    if i == 0:
        previous_residuals = np.concatenate((np.zeros(40), residuals))
    elif 0 < i < 12:
        previous_residuals = np.concatenate((previous_residuals, residuals))
    else:
        previous_residuals = np.concatenate((previous_residuals, residuals))

    # debugging
    print(f'previous_residuals for {i} of {len(previous_residuals)}')
    print(previous_residuals)


    # this is all about the plot for every validations
    # this is all about the plot for every validations
    if 0<=i<8:
      td_plot = true_data.values if hasattr(true_data, 'values') else np.array(true_data)
      ax[i].plot(pred_epiweeks, td_plot, marker='o', linestyle='-', color='blue', linewidth=1, label='True cases')
      ax[i].plot(pred_epiweeks, model_forecast.squeeze(), marker='o', linestyle='-', color='red', linewidth=2, label='Forecasting')
      tick_start = y_start
      tick_end = y_end
      new_tick_positions = np.array(dfm[dfm['epiweek'].between(y_start, y_end)]['epiweek'])
      tick_labels = [f'{int(week):04d}' for week in new_tick_positions]
      ax[i].set_xticks(new_tick_positions)
      ax[i].set_xticklabels(tick_labels, rotation=90)
      ax[i].set_xlim([tick_start, tick_end])
      ax[i].legend(frameon=False)
      ax[i].set_title(f'Forecasting on Level {i} for State: {selected_state_name}')
      print(f'Level {i + 1} - Tick Start: {tick_start}, Tick End: {tick_end}, Positions: {new_tick_positions}')
      td_mse = true_data if isinstance(true_data, np.ndarray) else true_data.values
      mf_mse = model_forecast.squeeze()
      n_m = min(len(td_mse), len(mf_mse))
      mse = mean_squared_error(td_mse[:n_m], mf_mse[:n_m])
      mse_scores.append(mse)
      print(f'Mean squared error : {mse} when training level is i : {i}')

    elif i==8:
      forecasting_y_start = 202241
      forecasting_y_end   = 202340
      forecasting_pred_epiweeks = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)]['epiweek']
      forecasting_true_data     = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)][selected_state_name]
      model_forecast = all_model_forecasts[8].flatten()
      if len(forecasting_pred_epiweeks) != len(model_forecast):
        model_forecast = model_forecast[:len(forecasting_pred_epiweeks)]
      ax[i].plot(forecasting_pred_epiweeks, forecasting_true_data.values, marker='o', linestyle='-', color='blue', linewidth=1, label='True cases')
      ax[i].plot(forecasting_pred_epiweeks, model_forecast, marker='o', linestyle='-', color='red', linewidth=2, label='Forecasting')
      tick_start = forecasting_y_start
      tick_end   = forecasting_y_end
      new_tick_positions = np.array(forecasting_pred_epiweeks)  # ← FIXED
      tick_labels = [f'{int(week):04d}' for week in new_tick_positions]
      ax[i].set_xticks(new_tick_positions)
      ax[i].set_xticklabels(tick_labels, rotation=90)
      ax[i].set_xlim([tick_start, tick_end])
      ax[i].legend(frameon=False)
      ax[i].set_title(f'Validation Test 1 (2022–2023) for State: {selected_state_name}')
      print(f'Level {i + 1} - Tick Start: {tick_start}, Tick End: {tick_end}, Positions: {new_tick_positions}')
      td_mse = true_data if isinstance(true_data, np.ndarray) else true_data.values
      mf_mse = model_forecast.squeeze()
      n_m = min(len(td_mse), len(mf_mse))
      mse = mean_squared_error(td_mse[:n_m], mf_mse[:n_m])
      mse_scores.append(mse)
      print(f'Mean squared error : {mse} when training level is i : {i}')
      print(f'for {i} forecasting length {len(model_forecast)} and pred length {len(forecasting_pred_epiweeks)}')
      print(model_forecast)

    elif i==9:
      forecasting_y_start = 202341
      forecasting_y_end   = 202440
      forecasting_pred_epiweeks = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)]['epiweek']
      forecasting_true_data     = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)][selected_state_name]
      model_forecast = all_model_forecasts[9].flatten()
      if len(forecasting_pred_epiweeks) != len(model_forecast):
        model_forecast = model_forecast[:len(forecasting_pred_epiweeks)]
      ax[i].plot(forecasting_pred_epiweeks, forecasting_true_data.values, marker='o', linestyle='-', color='blue', linewidth=1, label='True cases')
      ax[i].plot(forecasting_pred_epiweeks, model_forecast, marker='o', linestyle='-', color='red', linewidth=2, label='Forecasting')
      tick_start = forecasting_y_start
      tick_end   = forecasting_y_end
      new_tick_positions = np.array(forecasting_pred_epiweeks)  # ← FIXED
      tick_labels = [f'{int(week):04d}' for week in new_tick_positions]
      ax[i].set_xticks(new_tick_positions)
      ax[i].set_xticklabels(tick_labels, rotation=90)
      ax[i].set_xlim([tick_start, tick_end])
      ax[i].legend(frameon=False)
      ax[i].set_title(f'Validation Test 2 (2023–2024) for State: {selected_state_name}')
      print(f'Level {i + 1} - Tick Start: {tick_start}, Tick End: {tick_end}, Positions: {new_tick_positions}')
      td_mse = true_data if isinstance(true_data, np.ndarray) else true_data.values
      mf_mse = model_forecast.squeeze()
      n_m = min(len(td_mse), len(mf_mse))
      mse = mean_squared_error(td_mse[:n_m], mf_mse[:n_m])
      mse_scores.append(mse)
      print(f'Mean squared error : {mse} when training level is i : {i}')
      print(f'for {i} forecasting length {len(model_forecast)} and pred length {len(forecasting_pred_epiweeks)}')
      print(model_forecast)

    elif i==10:
      forecasting_y_start = 202441
      forecasting_y_end   = 202540
      forecasting_pred_epiweeks = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)]['epiweek']
      forecasting_true_data     = dfm[dfm['epiweek'].between(forecasting_y_start, forecasting_y_end)][selected_state_name]
      model_forecast = all_model_forecasts[10].flatten()
      if len(forecasting_pred_epiweeks) != len(model_forecast):
        model_forecast = model_forecast[:len(forecasting_pred_epiweeks)]
      ax[i].plot(forecasting_pred_epiweeks, forecasting_true_data.values[:len(forecasting_pred_epiweeks)], marker='o', linestyle='-', color='blue', linewidth=1, label='True cases')  # ← FIXED
      ax[i].plot(forecasting_pred_epiweeks, model_forecast, marker='o', linestyle='-', color='red', linewidth=2, label='Forecasting')
      tick_start = forecasting_y_start
      tick_end   = forecasting_y_end
      new_tick_positions = np.array(forecasting_pred_epiweeks)  # ← FIXED
      tick_labels = [f'{int(week):04d}' for week in new_tick_positions]
      ax[i].set_xticks(new_tick_positions)
      ax[i].set_xticklabels(tick_labels, rotation=90)
      ax[i].set_xlim([tick_start, tick_end])
      ax[i].legend(frameon=False)
      ax[i].set_title(f'Validation Test 3 (2024–2025) for State: {selected_state_name}')
      print(f'Level {i + 1} - Tick Start: {tick_start}, Tick End: {tick_end}, Positions: {new_tick_positions}')
      td_mse = true_data if isinstance(true_data, np.ndarray) else true_data.values
      mf_mse = model_forecast.squeeze()
      n_m = min(len(td_mse), len(mf_mse))
      mse = mean_squared_error(td_mse[:n_m], mf_mse[:n_m])
      mse_scores.append(mse)
      print(f'Mean squared error : {mse} when training level is i : {i}')
      print(f'for {i} forecasting length {len(model_forecast)} and pred length {len(forecasting_pred_epiweeks)}   with i : {i}')
      print(model_forecast)

    elif i == 11:
      # forecasting_y_start = 202541
      # true_y_end          = 202610
      # forecasting_pred_epiweeks = np.concatenate([
      #     dfm[dfm['epiweek'].between(forecasting_y_start, true_y_end)]['epiweek'].values,
      #     np.arange(
      #         dfm[dfm['epiweek'] <= true_y_end]['epiweek'].iloc[-1] + 1,
      #         dfm[dfm['epiweek'] <= true_y_end]['epiweek'].iloc[-1] + 1 +
      #         (len(model_forecast) - n_obs)
      #     )
      # ])
      forecasting_y_start = 202541
      forecasting_y_end   = 202641
      true_y_end          = 202610

      # Epiweeks that exist in dfm (202541 → 202610)
      existing_epiweeks = dfm[dfm['epiweek'].between(
          forecasting_y_start, true_y_end)]['epiweek'].values

      # Missing epiweeks that don't exist in dfm yet (202611 → 202641)
      missing_epiweeks = np.array([
          202611, 202612, 202613, 202614, 202615, 202616, 202617,
          202618, 202619, 202620, 202621, 202622, 202623, 202624,
          202625, 202626, 202627, 202628, 202629, 202630, 202631,
          202632, 202633, 202634, 202635, 202636, 202637, 202638,
          202639, 202640
      ])

      # Combine both
      forecasting_pred_epiweeks = np.concatenate([existing_epiweeks, missing_epiweeks])
      forecasting_pred_epiweeks
      len(forecasting_pred_epiweeks)
      forecasting_true_data     = dfm[dfm['epiweek'].between(forecasting_y_start, true_y_end)][selected_state_name]
      model_forecast = all_model_forecasts[11].flatten()
      if len(forecasting_pred_epiweeks) != len(model_forecast):
        model_forecast = model_forecast[:len(forecasting_pred_epiweeks)]
      # ax[i].plot(forecasting_pred_epiweeks[:len(forecasting_true_data)], forecasting_true_data.values, marker='o', linestyle='-', color='blue', linewidth=1, label='True cases')  # ← FIXED
      true_epiweeks = dfm[dfm['epiweek'].between(forecasting_y_start, true_y_end)]['epiweek']
      ax[i].plot(true_epiweeks,forecasting_true_data.values, marker='o', linestyle='-', color='blue', linewidth=1, label='True cases')
      ax[i].plot(forecasting_pred_epiweeks, model_forecast, marker='o', linestyle='-', color='red', linewidth=2, label='Forecasting')
      tick_start = forecasting_y_start
      tick_end   = forecasting_y_end
      new_tick_positions = np.array(forecasting_pred_epiweeks)  # ← FIXED
      tick_labels = [f'{int(week):04d}' for week in new_tick_positions]
      ax[i].set_xticks(new_tick_positions)
      ax[i].set_xticklabels(tick_labels, rotation=90)
      ax[i].set_xlim([tick_start, tick_end])
      ax[i].legend(frameon=False)
      ax[i].set_title(f'Validation Test 4 (2025–2026) for State: {selected_state_name}')
      print(f'Level {i + 1} - Tick Start: {tick_start}, Tick End: {tick_end}, Positions: {new_tick_positions}')
      td_mse = true_data if isinstance(true_data, np.ndarray) else true_data.values
      mf_mse = model_forecast.squeeze()
      n_m = min(len(td_mse), len(mf_mse))
      mse = mean_squared_error(td_mse[:n_m], mf_mse[:n_m])
      mse_scores.append(mse)
      print(f'Mean squared error : {mse} when training level is i : {i}')
      print(f'for {i} forecasting length {len(model_forecast)} and pred length {len(forecasting_pred_epiweeks)}   with i : {i}')
      print(model_forecast)

    else:  # i == 12
      forecasting_y_start = 202641
      forecasting_y_end   = 202740
      forecasting_pred_epiweeks = [
          202641, 202642, 202643, 202644, 202645, 202646, 202647,
          202648, 202649, 202650, 202651, 202652,
          202701, 202702, 202703, 202704, 202705, 202706, 202707,
          202708, 202709, 202710, 202711, 202712, 202713, 202714,
          202715, 202716, 202717, 202718, 202719, 202720, 202721,
          202722, 202723, 202724, 202725, 202726, 202727, 202728,
          202729, 202730, 202731, 202732, 202733, 202734, 202735,
          202736, 202737, 202738, 202739, 202740]
      model_forecast = all_model_forecasts[12].flatten()
      if len(forecasting_pred_epiweeks) != len(model_forecast):
        model_forecast = model_forecast[:len(forecasting_pred_epiweeks)]
      ax[i].plot(forecasting_pred_epiweeks, model_forecast, marker='o', linestyle='-', color='red', linewidth=2, label='Forecasting')
      tick_start = forecasting_y_start
      tick_end   = forecasting_y_end
      new_tick_positions = np.array(forecasting_pred_epiweeks)
      tick_labels = [f'{int(week):04d}' for week in new_tick_positions]
      ax[i].set_xticks(new_tick_positions)
      ax[i].set_xticklabels(tick_labels, rotation=90)
      ax[i].set_xlim([tick_start, tick_end])
      ax[i].legend(frameon=False)
      ax[i].set_title(f'Final Forecast (2026–2027) for State: {selected_state_name}')
      print(f'Level {i + 1} - Tick Start: {tick_start}, Tick End: {tick_end}, Positions: {new_tick_positions}')
      td_mse = true_data if isinstance(true_data, np.ndarray) else true_data.values
      mf_mse = model_forecast.squeeze()
      n_m = min(len(td_mse), len(mf_mse))
      mse = mean_squared_error(td_mse[:n_m], mf_mse[:n_m])
      mse_scores.append(mse)
      print(f'Mean squared error : {mse} when training level is i : {i}')
      print(f'for {i} forecasting length {len(model_forecast)} and pred length {len(forecasting_pred_epiweeks)}   with i : {i}')
      print(model_forecast)
      plt.show()

# total training mse scores
total_mse_scores_each_L = sum(mse_scores)

print(f'no_of_levels : {no_of_levels}')
print(f'n_steps: {n_steps}')
print(f'X shape: {X.shape}')
print(f'X_train shape: {X_train.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'X_test shape: {X_test.shape}')
# print(f'y_test shape: {y_test.shape}')
# print(f'Total MSE on the Prediction : {total_mse_scores_each_L} when L is {L}')
plt.tight_layout()
plt.show()



# Method 1: Flattening
all_residuals_output = X_train[:, :, 1].flatten()
new_X_train = X_train[:, :, 1]


# Define the file paths
x_train_path = os.path.join(forecast_dir_uf, f'{selected_state_name}_{model_name}_all_X_train.csv')
all_residuals_output_path = os.path.join(forecast_dir_uf, f'{selected_state_name}_{model_name}_all_residuals_output.csv')
forecast_path = os.path.join(forecast_dir_uf, f'{selected_state_name}_{model_name}_all_model_forecasts.csv')
all_model_r2_score_path = os.path.join(forecast_dir_uf, f'{selected_state_name}_{model_name}_all_model_r2_score.csv')


#save all_model_forecasts to CSV in row vector
# with open(forecast_path, 'w', newline='') as file:
#      writer = csv.writer(file)
#      for forecast in all_model_forecasts:
#          writer.writerow(forecast.flatten())

#save all_model_forecasts to CSV in column vector
max_len = max(arr.shape[0] for arr in all_model_forecasts)  # Determine the maximum length
# Pad arrays to have the same length
padded_forecasts = []
for arr in all_model_forecasts:
    if arr.shape[0] < max_len:
        # Pad with NaN or another value
        pad_width = max_len - arr.shape[0]
        padded_arr = np.pad(arr, ((0, pad_width), (0, 0)), mode='constant', constant_values=np.nan)
    else:
        padded_arr = arr
    padded_forecasts.append(padded_arr)
# Concatenate the padded arrays

forecasts_2d = np.hstack(padded_forecasts)
with open(forecast_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for forecast in forecasts_2d:
        writer.writerow(forecast.flatten())
        #writer.writerow([forecast])


# Save all_X_train to CSV
with open(x_train_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for x_train in all_X_trains:
        # Flatten array and save
        writer.writerow(x_train.flatten())
        #writer.writerow([x_train])

# Save all_residuals_output to CSV
# with open(all_residuals_output_path, 'w', newline='') as file:
#     writer = csv.writer(file)
    # for all_residuals in all_residuals_output:
    #     # Flatten array and save
    #     writer.writerow(all_residuals.flatten())
        # writer.writerow([r2_score])

with open(all_residuals_output_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for r in all_residuals_output:
        writer.writerow([r])                   # ← wraps the float in a list → writes one number per row


# Save all_model_r2_scoreto CSV
with open(all_model_r2_score_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for r2_score in all_model_r2_score:
        # Flatten array and save
        # writer.writerow(r2_score.flatten())
        writer.writerow([r2_score])


### save all the Validation tests and the forecast for 2025-2026 data

# Validation Test 1: 2022–2023 forecasting dates i =8
dates = [
    "2022-10-09", "2022-10-16", "2022-10-23", "2022-10-30", "2022-11-06", "2022-11-13",
    "2022-11-20", "2022-11-27", "2022-12-04", "2022-12-11", "2022-12-18", "2022-12-25",
    "2023-01-01", "2023-01-08", "2023-01-15", "2023-01-22", "2023-01-29", "2023-02-05",
    "2023-02-12", "2023-02-19", "2023-02-26", "2023-03-05", "2023-03-12", "2023-03-19",
    "2023-03-26", "2023-04-02", "2023-04-09", "2023-04-16", "2023-04-23", "2023-04-30",
    "2023-05-07", "2023-05-14", "2023-05-21", "2023-05-28", "2023-06-04", "2023-06-11",
    "2023-06-18", "2023-06-25", "2023-07-02", "2023-07-09", "2023-07-16", "2023-07-23",
    "2023-07-30", "2023-08-06", "2023-08-13", "2023-08-20", "2023-08-27", "2023-09-03",
    "2023-09-10", "2023-09-17", "2023-09-24", "2023-10-01"
]

# Z-scores for prediction intervals
z_scores = {
    '50': 0.674,
    '80': 1.282,
    '90': 1.645,
    '95': 1.960
}

# Forecast and residuals
pred = all_model_forecasts[8].flatten()  # Forecasts for validation test 1
residuals = all_X_trains[7][:, 15]       # Training residuals upto level 11
std_residuals = np.std(residuals)

# Compute prediction intervals
intervals = {}
for level, z in z_scores.items():
    intervals[f'lower_{level}'] = pred - z * std_residuals
    intervals[f'upper_{level}'] = pred + z * std_residuals

# Ensure no negative lower bounds
for key in intervals:
    if 'lower' in key:
        intervals[key][intervals[key] < 0] = 0

# Create DataFrame without adm_1
df = pd.DataFrame({
    'date': dates,
    'pred': pred,
    'lower_95': intervals['lower_95'],
    'lower_90': intervals['lower_90'],
    'lower_80': intervals['lower_80'],
    'lower_50': intervals['lower_50'],
    'upper_50': intervals['upper_50'],
    'upper_80': intervals['upper_80'],
    'upper_90': intervals['upper_90'],
    'upper_95': intervals['upper_95']
})

# Define the output path
os.makedirs(forecast_dir_uf, exist_ok=True)

csv_filename = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test1_2022_2023_forecast_intervals_2026.csv"

# Save the DataFrame to CSV
df.to_csv(csv_filename, index=False)

print(f"✅ File saved as: {csv_filename}")
# print(df.head())


# Validation Test 2: 2023–2024 forecasting dates i= 9
dates = [
    "2023-10-08", "2023-10-15", "2023-10-22", "2023-10-29", "2023-11-05", "2023-11-12",
    "2023-11-19", "2023-11-26", "2023-12-03", "2023-12-10", "2023-12-17", "2023-12-24",
    "2023-12-31", "2024-01-07", "2024-01-14", "2024-01-21", "2024-01-28", "2024-02-04",
    "2024-02-11", "2024-02-18", "2024-02-25", "2024-03-03", "2024-03-10", "2024-03-17",
    "2024-03-24", "2024-03-31", "2024-04-07", "2024-04-14", "2024-04-21", "2024-04-28",
    "2024-05-05", "2024-05-12", "2024-05-19", "2024-05-26", "2024-06-02", "2024-06-09",
    "2024-06-16", "2024-06-23", "2024-06-30", "2024-07-07", "2024-07-14", "2024-07-21",
    "2024-07-28", "2024-08-04", "2024-08-11", "2024-08-18", "2024-08-25", "2024-09-01",
    "2024-09-08", "2024-09-15", "2024-09-22", "2024-09-29"
]

# Z-scores for prediction intervals
z_scores = {
    '50': 0.674,
    '80': 1.282,
    '90': 1.645,
    '95': 1.960
}

# Forecast and residuals (replace these with your actual arrays)
pred = all_model_forecasts[9].flatten()  #  # Forecasts for validation test 2
residuals = all_X_trains[8][:, 15]       # Training residuals upto level 12

# Standard deviation of residuals
std_residuals = np.std(residuals)

# Compute prediction intervals
intervals = {}
for level, z in z_scores.items():
    intervals[f'lower_{level}'] = pred - z * std_residuals
    intervals[f'upper_{level}'] = pred + z * std_residuals

# Ensure no negative lower bounds
for key in intervals:
    if 'lower' in key:
        intervals[key][intervals[key] < 0] = 0

# Construct the final DataFrame
df = pd.DataFrame({
    'date': dates,
    'pred': pred,
    'lower_95': intervals['lower_95'],
    'lower_90': intervals['lower_90'],
    'lower_80': intervals['lower_80'],
    'lower_50': intervals['lower_50'],
    'upper_50': intervals['upper_50'],
    'upper_80': intervals['upper_80'],
    'upper_90': intervals['upper_90'],
    'upper_95': intervals['upper_95']
})

# Define output directory and ensure it exists
os.makedirs(forecast_dir_uf, exist_ok=True)

# Output file path
csv_filename = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test2_2023_2024_forecast_intervals_2026.csv"

# Save to CSV
df.to_csv(csv_filename, index=False)

print(f"✅ File saved as: {csv_filename}")
# print(df.head())


# Validation Test 3: 2024-2025 === Forecast dates === i = 10
dates = [
    "2024-10-06", "2024-10-13", "2024-10-20", "2024-10-27", "2024-11-03", "2024-11-10",
    "2024-11-17", "2024-11-24", "2024-12-01", "2024-12-08", "2024-12-15", "2024-12-22",
    "2024-12-29", "2025-01-05", "2025-01-12", "2025-01-19", "2025-01-26", "2025-02-02",
    "2025-02-09", "2025-02-16", "2025-02-23", "2025-03-02", "2025-03-09", "2025-03-16",
    "2025-03-23", "2025-03-30", "2025-04-06", "2025-04-13", "2025-04-20", "2025-04-27",
    "2025-05-04", "2025-05-11", "2025-05-18", "2025-05-25", "2025-06-01", "2025-06-08",
    "2025-06-15", "2025-06-22", "2025-06-29", "2025-07-06", "2025-07-13", "2025-07-20",
    "2025-07-27", "2025-08-03", "2025-08-10", "2025-08-17", "2025-08-24", "2025-08-31",
    "2025-09-07", "2025-09-14", "2025-09-21", "2025-09-28"
]

# === Z-scores for prediction intervals ===
z_scores = {
    '50': 0.674,
    '80': 1.282,
    '90': 1.645,
    '95': 1.960
}

# === Forecast and residuals ===
pred = all_model_forecasts[10].flatten()      # Forecasts for validation test 3
residuals = all_X_trains[9][:, 15]          # Training residuals upto level 13

# === Standard deviation of residuals ===
std_residuals = np.std(residuals)

# === Compute prediction intervals ===
intervals = {}
for level, z in z_scores.items():
    intervals[f'lower_{level}'] = pred - z * std_residuals
    intervals[f'upper_{level}'] = pred + z * std_residuals

# === Clip negative lower bounds to 0 ===
for key in intervals:
    if 'lower' in key:
        intervals[key] = np.clip(intervals[key], 0, None)

# === Create DataFrame ===
df = pd.DataFrame({
    'date': dates,
    'pred': pred,
    'lower_95': intervals['lower_95'],
    'lower_90': intervals['lower_90'],
    'lower_80': intervals['lower_80'],
    'lower_50': intervals['lower_50'],
    'upper_50': intervals['upper_50'],
    'upper_80': intervals['upper_80'],
    'upper_90': intervals['upper_90'],
    'upper_95': intervals['upper_95']
})

# === Save CSV ===

csv_filename = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test3_2024_2025_forecast_intervals_2026.csv"
df.to_csv(csv_filename, index=False)

print(f"✅ File saved as: {csv_filename}")
# print(df.head())


# Validation Test 4: 2025–2026 (i=11) ─────────────────────
dates =  [
        "2025-10-05","2025-10-12","2025-10-19","2025-10-26","2025-11-02","2025-11-09",
        "2025-11-16","2025-11-23","2025-11-30","2025-12-07","2025-12-14","2025-12-21",
        "2025-12-28","2026-01-04","2026-01-11","2026-01-18","2026-01-25","2026-02-01",
        "2026-02-08","2026-02-15","2026-02-22","2026-03-01","2026-03-08","2026-03-15",
        "2026-03-22","2026-03-29","2026-04-05","2026-04-12","2026-04-19","2026-04-26",
        "2026-05-03","2026-05-10","2026-05-17","2026-05-24","2026-05-31","2026-06-07",
        "2026-06-14","2026-06-21","2026-06-28","2026-07-05","2026-07-12","2026-07-19",
        "2026-07-26","2026-08-02","2026-08-09","2026-08-16","2026-08-23","2026-08-30",
        "2026-09-06","2026-09-13","2026-09-20","2026-09-27", "2026-10-04"]

# === Z-scores for prediction intervals ===
z_scores = {
    '50': 0.674,
    '80': 1.282,
    '90': 1.645,
    '95': 1.960
}

# === Get predictions and residuals ===
pred          = all_model_forecasts[11].flatten()  # Forecasts for validation test 4
residuals     = all_X_trains[10][:, 15]            # Training residuals upto level 14
std_residuals = np.std(residuals)                  # Standard deviation of residuals

# === Compute prediction intervals ===
intervals = {}
for level, z in z_scores.items():
    intervals[f'lower_{level}'] = np.clip(pred - z * std_residuals, 0, None)
    intervals[f'upper_{level}'] = np.clip(pred + z * std_residuals, 0, None)

# === Create DataFrame ===
df = pd.DataFrame({
    'date': dates,
    'pred': pred,
    'lower_95': intervals['lower_95'],
    'lower_90': intervals['lower_90'],
    'lower_80': intervals['lower_80'],
    'lower_50': intervals['lower_50'],
    'upper_50': intervals['upper_50'],
    'upper_80': intervals['upper_80'],
    'upper_90': intervals['upper_90'],
    'upper_95': intervals['upper_95'],
})

# === Save the data at the file ===

csv_filename = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test4_2025_2026_forecast_intervals_2026.csv"

# === Save CSV ===
df.to_csv(csv_filename, index=False)

print(f"✅ File saved as: {csv_filename}")


# Final Forecast Phase: 2026–2027 (i=12) ────────────────────────
dates = [
        "2026-10-11","2026-10-18","2026-10-25","2026-11-01","2026-11-08",
        "2026-11-15","2026-11-22","2026-11-29","2026-12-06","2026-12-13","2026-12-20",
        "2026-12-27","2027-01-03","2027-01-10","2027-01-17","2027-01-24","2027-01-31",
        "2027-02-07","2027-02-14","2027-02-21","2027-02-28","2027-03-07","2027-03-14",
        "2027-03-21","2027-03-28","2027-04-04","2027-04-11","2027-04-18","2027-04-25",
        "2027-05-02","2027-05-09","2027-05-16","2027-05-23","2027-05-30","2027-06-06",
        "2027-06-13","2027-06-20","2027-06-27","2027-07-04","2027-07-11","2027-07-18",
        "2027-07-25","2027-08-01","2027-08-08","2027-08-15","2027-08-22","2027-08-29",
        "2027-09-05","2027-09-12","2027-09-19","2027-09-26", "2027-10-03"
]

# === Z-scores for prediction intervals ===
z_scores = {
    '50': 0.674,
    '80': 1.282,
    '90': 1.645,
    '95': 1.960
}

# === Get predictions and residuals ===
pred = all_model_forecasts[12].flatten()    #  # Forecasts for validation test 5 or Final Forecasts
residuals = all_X_trains[11][:, 15]         # Training residuals upto level 15
std_residuals = np.std(residuals)           # Standard deviation of residuals

# === Compute prediction intervals ===
intervals = {}
for level, z in z_scores.items():
    intervals[f'lower_{level}'] = np.clip(pred - z * std_residuals, 0, None)
    intervals[f'upper_{level}'] = np.clip(pred + z * std_residuals, 0, None)

# === Create DataFrame ===
df = pd.DataFrame({
    'date': dates,
    'pred': pred,
    'lower_95': intervals['lower_95'],
    'lower_90': intervals['lower_90'],
    'lower_80': intervals['lower_80'],
    'lower_50': intervals['lower_50'],
    'upper_50': intervals['upper_50'],
    'upper_80': intervals['upper_80'],
    'upper_90': intervals['upper_90'],
    'upper_95': intervals['upper_95'],
})

# === Define output directory and file name ===

csv_filename = f"{forecast_dir_uf}/{selected_state_name}_final_forecasts_2026_2027_forecast_intervals_2026.csv"

# === Save CSV ===
df.to_csv(csv_filename, index=False)

print(f"✅ File saved as: {csv_filename}")
# print(df.head())

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 2 — BPI (Nguinabé et al. 2025)
# ═══════════════════════════════════════════════════════════════════════════════

# ── BPI parameters ────────────────────────────────────────────────────────────
BPI_B            = 50           # fixed per Nguinabé et al. 2025
BPI_epochs       = 50           # sufficient for bootstrap models
BPI_block_size   = 4            # 4-week MBB blocks
BPI_kernel       = 1
BPI_lr           = 0.0001
BPI_filters_list = filters_vec  # [256, 512]


def get_Xtrain_3d(level_idx):
    flat = all_X_trains[level_idx]
    return flat.reshape(flat.shape[0], n_steps, n_features)

def get_ytrain(level_idx):
    return all_y_trains[level_idx]

def bpi_cnn_lstm_ensemble(X_train_3d, y_train_1d, X_test_3d,
                           point_forecast,              # ← ADD
                           filters_list, kernel_size, learning_rate,
                           n_steps, n_features,
                           B=50, block_size=4, epochs=50,
                           quantiles=(0.025, 0.05, 0.10, 0.25,
                                      0.75, 0.90, 0.95, 0.975)):

    """
    BPI using multiple filters — runs B bootstrap resamples for EACH filter,
    then pools all predictions before computing quantiles.
    With filters_list=[256,512] and B=50 → 100 total predictions per week.
    """
    n        = len(X_train_3d)
    nob      = n - block_size + 1
    n_blocks = int(np.ceil(n / block_size))
    H        = len(X_test_3d)

    all_boot_rows = []

    for filters in filters_list:
        print(f"    filter={filters}: running {B} bootstrap resamples ...")
        boot_matrix = np.zeros((B, H))

        for b in range(B):
            # Randomly resample the training data by selecting consecutive time blocks.
            # This creates different training datasets while preserving temporal dependence.
            starts  = np.random.randint(0, nob, size=n_blocks)
            idx     = np.concatenate(
                          [np.arange(s, s + block_size) for s in starts])[:n]
            X_boot  = X_train_3d[idx]
            y_boot  = y_train_1d[idx]
            # Train a new CNN-LSTM model on each bootstrap sample.
            # Different bootstrap samples and random model initialization produce
            # multiple possible forecasts used to quantify prediction uncertainty.
            m = build_cnn_lstm_model(
                    filters, kernel_size, learning_rate, n_steps, n_features)
            m.fit(X_boot, y_boot, epochs=epochs,
                  validation_split=0.1, batch_size=5, verbose=0)

            boot_matrix[b] = m.predict(X_test_3d, verbose=0).flatten()[:H]

        all_boot_rows.append(boot_matrix)

    pooled = np.vstack(all_boot_rows)
    print(f"    pooled bootstrap matrix: {pooled.shape} "
          f"({len(filters_list)} filters × {B} resamples)")

    # # center bootstrap distribution on Cell 1 point forecast and boot strapping PI
    # boot_mean = np.mean(pooled, axis=0)
    # residuals = pooled - boot_mean
    # centered  = point_forecast + residuals
    # centered  = np.clip(centered, 0, None)

    # bpi = {}
    # bpi['pred'] = np.clip(point_forecast, 0, None)   # ← Cell 1 as point forecast
    # for q in quantiles:
    #     bpi[q] = np.percentile(centered, q * 100, axis=0)
    # return bpi


    # Combined point forecast: Cell 1 ensemble + bootstrap mean
    # alpha=0.5: equal weight — uses Cell 1 residual knowledge + bootstrap stability

    # Combine the original point forecast with the average bootstrap forecast.
    # alpha=0.5 gives equal weight to the original model forecast and bootstrap ensemble mean.

    # boot_mean  = np.mean(pooled, axis=0)
    # alpha      = 0.5
    # final_pred = alpha * point_forecast + (1 - alpha) * boot_mean
    # final_pred = np.clip(final_pred, 0, None)

    # bpi = {}
    # bpi['pred'] = final_pred                  # ← combined point forecast
    # for q in quantiles:
    #     bpi[q] = np.clip(
    #         np.percentile(pooled, q * 100, axis=0), 0, None)
    # return bpi

    # Combined point forecast: Cell 1 ensemble + bootstrap mean
    # alpha=0.5: equal weight — uses Cell 1 residual knowledge + bootstrap stability
    boot_mean  = np.mean(pooled, axis=0)
    alpha      = 0.5
    final_pred = alpha * point_forecast + (1 - alpha) * boot_mean
    final_pred = np.clip(final_pred, 0, None)

    # Recentre bootstrap deviations on final_pred
    # → guarantees intervals always bracket final_pred by construction
    boot_residuals = pooled - boot_mean       # (100, H) deviations; mean = 0
    centered       = final_pred + boot_residuals  # shift to final_pred; mean = final_pred

    bpi = {}
    bpi['pred'] = final_pred                  # ← combined point forecast
    for q in quantiles:
        bpi[q] = np.clip(
            np.percentile(centered, q * 100, axis=0), 0, None)
    return bpi



os.makedirs(forecast_dir_uf, exist_ok=True)

print(f"BPI settings: B={BPI_B} per filter, epochs={BPI_epochs}, "
      f"filters={BPI_filters_list}")
print(f"Total bootstrap predictions per level: "
      f"{BPI_B * len(BPI_filters_list)} "
      f"({BPI_B} × {len(BPI_filters_list)} filters)")
print("─" * 60)

print("▶ BPI i=8 (Validation Test 1: 2022–2023) ...")

bpi_12 = bpi_cnn_lstm_ensemble(
    get_Xtrain_3d(7), get_ytrain(7), fake_X_pred_12,
    point_forecast=all_model_forecasts[8].flatten(),
    filters_list=BPI_filters_list, kernel_size=BPI_kernel,
    learning_rate=BPI_lr, n_steps=n_steps, n_features=n_features,
    B=BPI_B, block_size=BPI_block_size, epochs=BPI_epochs)

np.save(f"{forecast_dir_uf}/bpi_12.npy", bpi_12)
print("✅ BPI i=8 done — saved\n")



print("▶ BPI i=9 (Validation Test 2: 2023–2024) ...")

bpi_13 = bpi_cnn_lstm_ensemble(
    get_Xtrain_3d(8), get_ytrain(8), fake_X_pred_13,
    point_forecast=all_model_forecasts[9].flatten(),
    filters_list=BPI_filters_list, kernel_size=BPI_kernel,
    learning_rate=BPI_lr, n_steps=n_steps, n_features=n_features,
    B=BPI_B, block_size=BPI_block_size, epochs=BPI_epochs)
np.save(f"{forecast_dir_uf}/bpi_13.npy", bpi_13)
print("✅ BPI i=9 done — saved\n")

print("▶ BPI i=10 (Validation Test 3: 2024–2025) ...")

bpi_14 = bpi_cnn_lstm_ensemble(
    get_Xtrain_3d(9), get_ytrain(9), fake_X_pred_14,
    point_forecast=all_model_forecasts[10].flatten(),
    filters_list=BPI_filters_list, kernel_size=BPI_kernel,
    learning_rate=BPI_lr, n_steps=n_steps, n_features=n_features,
    B=BPI_B, block_size=BPI_block_size, epochs=BPI_epochs)

np.save(f"{forecast_dir_uf}/bpi_14.npy", bpi_14)
print("✅ BPI i=10 done — saved\n")

print("▶ BPI i=11 (Validation Test 4: 2025–2026, 53 weeks) ...")

bpi_15 = bpi_cnn_lstm_ensemble(
    get_Xtrain_3d(10), get_ytrain(10), fake_X_pred_15,
    point_forecast=all_model_forecasts[11].flatten(),
    filters_list=BPI_filters_list, kernel_size=BPI_kernel,
    learning_rate=BPI_lr, n_steps=n_steps, n_features=n_features,
    B=BPI_B, block_size=BPI_block_size, epochs=BPI_epochs)

np.save(f"{forecast_dir_uf}/bpi_15.npy", bpi_15)
print("✅ BPI i=11 done — saved\n")

print("▶ BPI i=12 (Final Forecast: 2026–2027) ...")

bpi_16 = bpi_cnn_lstm_ensemble(
    get_Xtrain_3d(11), get_ytrain(11), fake_X_pred_16,
    point_forecast=all_model_forecasts[12].flatten(),
    filters_list=BPI_filters_list, kernel_size=BPI_kernel,
    learning_rate=BPI_lr, n_steps=n_steps, n_features=n_features,
    B=BPI_B, block_size=BPI_block_size, epochs=BPI_epochs)

np.save(f"{forecast_dir_uf}/bpi_16.npy", bpi_16)
print("✅ BPI i=12 done — saved\n")

print("=" * 60)
print("All BPI intervals computed and saved. Ready for Cell 3.")

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 3 — Save CSVs using BPI intervals
# ═══════════════════════════════════════════════════════════════════════════════

# Save the misc model data (unchanged from your original)
if not os.path.exists(forecast_dir_uf):
    os.makedirs(forecast_dir_uf)

all_residuals_output = X_train[:, :, 1].flatten()
new_X_train          = X_train[:, :, 1]

x_train_path              = os.path.join(forecast_dir_uf, f'{selected_state_name}_{model_name}_all_X_train.csv')
all_residuals_output_path = os.path.join(forecast_dir_uf, f'{selected_state_name}_{model_name}_all_residuals_output.csv')
forecast_path             = os.path.join(forecast_dir_uf, f'{selected_state_name}_{model_name}_all_model_forecasts.csv')
all_model_r2_score_path   = os.path.join(forecast_dir_uf, f'{selected_state_name}_{model_name}_all_model_r2_score.csv')

max_len = max(arr.shape[0] for arr in all_model_forecasts)

padded_forecasts = []

for arr in all_model_forecasts:
    pad_width  = max_len - arr.shape[0]
    padded_arr = np.pad(arr, ((0, pad_width), (0, 0)), mode='constant',
                        constant_values=np.nan) if pad_width > 0 else arr
    padded_forecasts.append(padded_arr)
forecasts_2d = np.hstack(padded_forecasts)
with open(forecast_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for forecast in forecasts_2d:
        writer.writerow(forecast.flatten())

with open(x_train_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for x_train in all_X_trains:
        writer.writerow(x_train.flatten())

# with open(all_residuals_output_path, 'w', newline='') as file:
#     writer = csv.writer(file)
#     for r in all_residuals_output:
#         writer.writerow(r.flatten())

with open(all_residuals_output_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for r in all_residuals_output:
        writer.writerow([r])

with open(all_model_r2_score_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for r2 in all_model_r2_score:
        writer.writerow([r2])


# ── helper: build DataFrame and save ─────────────────────────────────────────
def save_bpi_csv(dates, bpi, filepath):
    n = len(dates)
    pd.DataFrame({
        'date'     : dates,
        'pred'     : bpi['pred'][:n],
        'lower_95' : bpi[0.025][:n],
        'lower_90' : bpi[0.05] [:n],
        'lower_80' : bpi[0.10] [:n],
        'lower_50' : bpi[0.25] [:n],
        'upper_50' : bpi[0.75] [:n],
        'upper_80' : bpi[0.90] [:n],
        'upper_90' : bpi[0.95] [:n],
        'upper_95' : bpi[0.975][:n],
    }).to_csv(filepath, index=False)
    print(f"✅ Saved: {filepath}")


os.makedirs(forecast_dir_uf, exist_ok=True)


# Validation Test 1: 2022–2023 (i=8)
save_bpi_csv(
    dates=[
        "2022-10-09","2022-10-16","2022-10-23","2022-10-30","2022-11-06","2022-11-13",
        "2022-11-20","2022-11-27","2022-12-04","2022-12-11","2022-12-18","2022-12-25",
        "2023-01-01","2023-01-08","2023-01-15","2023-01-22","2023-01-29","2023-02-05",
        "2023-02-12","2023-02-19","2023-02-26","2023-03-05","2023-03-12","2023-03-19",
        "2023-03-26","2023-04-02","2023-04-09","2023-04-16","2023-04-23","2023-04-30",
        "2023-05-07","2023-05-14","2023-05-21","2023-05-28","2023-06-04","2023-06-11",
        "2023-06-18","2023-06-25","2023-07-02","2023-07-09","2023-07-16","2023-07-23",
        "2023-07-30","2023-08-06","2023-08-13","2023-08-20","2023-08-27","2023-09-03",
        "2023-09-10","2023-09-17","2023-09-24","2023-10-01"],
    #pred_flat = all_model_forecasts[12].flatten(),
    bpi       = bpi_12,
    filepath  = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test1_2022_2023_forecast_intervals_2026_BPI.csv"
)

# Validation Test 2: 2023–2024 (i=9)
save_bpi_csv(
    dates=[
        "2023-10-08","2023-10-15","2023-10-22","2023-10-29","2023-11-05","2023-11-12",
        "2023-11-19","2023-11-26","2023-12-03","2023-12-10","2023-12-17","2023-12-24",
        "2023-12-31","2024-01-07","2024-01-14","2024-01-21","2024-01-28","2024-02-04",
        "2024-02-11","2024-02-18","2024-02-25","2024-03-03","2024-03-10","2024-03-17",
        "2024-03-24","2024-03-31","2024-04-07","2024-04-14","2024-04-21","2024-04-28",
        "2024-05-05","2024-05-12","2024-05-19","2024-05-26","2024-06-02","2024-06-09",
        "2024-06-16","2024-06-23","2024-06-30","2024-07-07","2024-07-14","2024-07-21",
        "2024-07-28","2024-08-04","2024-08-11","2024-08-18","2024-08-25","2024-09-01",
        "2024-09-08","2024-09-15","2024-09-22","2024-09-29"],
    #pred_flat = all_model_forecasts[13].flatten(),
    bpi       = bpi_13,
    filepath  = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test2_2023_2024_forecast_intervals_2026_BPI.csv"
)

# Validation Test 3: 2024–2025 (i=10)
save_bpi_csv(
    dates=[
        "2024-10-06","2024-10-13","2024-10-20","2024-10-27","2024-11-03","2024-11-10",
        "2024-11-17","2024-11-24","2024-12-01","2024-12-08","2024-12-15","2024-12-22",
        "2024-12-29","2025-01-05","2025-01-12","2025-01-19","2025-01-26","2025-02-02",
        "2025-02-09","2025-02-16","2025-02-23","2025-03-02","2025-03-09","2025-03-16",
        "2025-03-23","2025-03-30","2025-04-06","2025-04-13","2025-04-20","2025-04-27",
        "2025-05-04","2025-05-11","2025-05-18","2025-05-25","2025-06-01","2025-06-08",
        "2025-06-15","2025-06-22","2025-06-29","2025-07-06","2025-07-13","2025-07-20",
        "2025-07-27","2025-08-03","2025-08-10","2025-08-17","2025-08-24","2025-08-31",
        "2025-09-07","2025-09-14","2025-09-21","2025-09-28"],
    #pred_flat = all_model_forecasts[14].flatten(),
    bpi       = bpi_14,
    filepath  = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test3_2024_2025_forecast_intervals_2026_BPI.csv"
)

# Validation Test 4: 2025–2026 (i=11) — 53 weeks
save_bpi_csv(
    dates=[
        "2025-10-05","2025-10-12","2025-10-19","2025-10-26","2025-11-02","2025-11-09",
        "2025-11-16","2025-11-23","2025-11-30","2025-12-07","2025-12-14","2025-12-21",
        "2025-12-28","2026-01-04","2026-01-11","2026-01-18","2026-01-25","2026-02-01",
        "2026-02-08","2026-02-15","2026-02-22","2026-03-01","2026-03-08","2026-03-15",
        "2026-03-22","2026-03-29","2026-04-05","2026-04-12","2026-04-19","2026-04-26",
        "2026-05-03","2026-05-10","2026-05-17","2026-05-24","2026-05-31","2026-06-07",
        "2026-06-14","2026-06-21","2026-06-28","2026-07-05","2026-07-12","2026-07-19",
        "2026-07-26","2026-08-02","2026-08-09","2026-08-16","2026-08-23","2026-08-30",
        "2026-09-06","2026-09-13","2026-09-20","2026-09-27","2026-10-04"],
    #pred_flat = all_model_forecasts[15].flatten(),
    bpi       = bpi_15,
    filepath  = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test4_2025_2026_forecast_intervals_2026_BPI.csv"
)

# Final Forecast: 2026–2027 (i=16)
save_bpi_csv(
    dates=[
        "2026-10-11","2026-10-18","2026-10-25","2026-11-01","2026-11-08",
        "2026-11-15","2026-11-22","2026-11-29","2026-12-06","2026-12-13","2026-12-20",
        "2026-12-27","2027-01-03","2027-01-10","2027-01-17","2027-01-24","2027-01-31",
        "2027-02-07","2027-02-14","2027-02-21","2027-02-28","2027-03-07","2027-03-14",
        "2027-03-21","2027-03-28","2027-04-04","2027-04-11","2027-04-18","2027-04-25",
        "2027-05-02","2027-05-09","2027-05-16","2027-05-23","2027-05-30","2027-06-06",
        "2027-06-13","2027-06-20","2027-06-27","2027-07-04","2027-07-11","2027-07-18",
        "2027-07-25","2027-08-01","2027-08-08","2027-08-15","2027-08-22","2027-08-29",
        "2027-09-05","2027-09-12","2027-09-19","2027-09-26","2027-10-03"],
    #pred_flat = all_model_forecasts[16].flatten(),
    bpi       = bpi_16,
    filepath  = f"{forecast_dir_uf}/{selected_state_name}_final_forecasts_2026_2027_forecast_intervals_2026_BPI.csv"
)


# ═══════════════════════════════════════════════════════════════════════════════
# CELL 4 — Plot BPI intervals + point forecast + true cases (run after Cell 3)
# Requires from Cell 1: dfm, selected_state_name
# Reads the _BPI.csv files saved by Cell 3.
# ═══════════════════════════════════════════════════════════════════════════════


COLORS = {
    '95': '#d0e4f7',
    '90': '#a8cce8',
    '80': '#6aaed6',
    '50': '#2171b5',
}

def get_true_from_dfm(ew_start, ew_end, dates_in_csv):
    values = dfm[dfm['epiweek'].between(ew_start, ew_end)][selected_state_name].values
    dates  = pd.to_datetime(dates_in_csv)
    n      = min(len(values), len(dates))
    return pd.Series(values[:n], index=dates[:n])

def plot_bpi(csv_path, title, true_series=None, save_path=None):
    df_plot = pd.read_csv(csv_path, parse_dates=['date'])
    fig, ax = plt.subplots(figsize=(18, 5))

    for level in ['95', '90', '80', '50']:
        ax.fill_between(df_plot['date'],
                        df_plot[f'lower_{level}'],
                        df_plot[f'upper_{level}'],
                        color=COLORS[level], alpha=0.9, label=f'{level}% PI')

    ax.plot(df_plot['date'], df_plot['pred'],
            color='red', linewidth=2, marker='o', markersize=3, label='Forecast')

    if true_series is not None:
        common = df_plot['date'][df_plot['date'].isin(true_series.index)]
        ax.plot(common, true_series.reindex(common).values,
                color='black', linewidth=1.5, marker='s', markersize=3,
                label='True cases')

    ax.set_title(title, fontsize=13)
    ax.set_xlabel('Date')
    ax.set_ylabel('Dengue cases')
    ax.legend(frameon=False, ncol=6, fontsize=9)
    ax.xaxis.set_major_locator(plt.MaxNLocator(20))
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()

    if save_path:
        fig.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f'✅ Plot saved: {save_path}')
    plt.show()
    plt.close(fig)

# VT1
csv1 = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test1_2022_2023_forecast_intervals_2026_BPI.csv"
plot_bpi(csv1, f'Validation Test 1 (2022–2023) — {selected_state_name}',
         true_series=get_true_from_dfm(202241, 202340, pd.read_csv(csv1)['date']),
         save_path=f"{forecast_dir_uf}/{selected_state_name}_VT1_2022_2023_BPI_plot.png")

# VT2
csv2 = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test2_2023_2024_forecast_intervals_2026_BPI.csv"
plot_bpi(csv2, f'Validation Test 2 (2023–2024) — {selected_state_name}',
         true_series=get_true_from_dfm(202341, 202440, pd.read_csv(csv2)['date']),
         save_path=f"{forecast_dir_uf}/{selected_state_name}_VT2_2023_2024_BPI_plot.png")

# VT3
csv3 = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test3_2024_2025_forecast_intervals_2026_BPI.csv"
plot_bpi(csv3, f'Validation Test 3 (2024–2025) — {selected_state_name}',
         true_series=get_true_from_dfm(202441, 202540, pd.read_csv(csv3)['date']),
         save_path=f"{forecast_dir_uf}/{selected_state_name}_VT3_2024_2025_BPI_plot.png")

# VT4 — true cases only up to EW10 2026
csv4 = f"{forecast_dir_uf}/{selected_state_name}_Validation_Test4_2025_2026_forecast_intervals_2026_BPI.csv"
plot_bpi(csv4, f'Validation Test 4 (2025–2026) — {selected_state_name} | true up to EW10 2026',
         true_series=get_true_from_dfm(202541, 202610, pd.read_csv(csv4)['date']),
         save_path=f"{forecast_dir_uf}/{selected_state_name}_VT4_2025_2026_BPI_plot.png")

# Final Forecast — no true cases
csv5 = f"{forecast_dir_uf}/{selected_state_name}_final_forecasts_2026_2027_forecast_intervals_2026_BPI.csv"
plot_bpi(csv5, f'Final Forecast (2026–2027) — {selected_state_name}',
         true_series=None,
         save_path=f"{forecast_dir_uf}/{selected_state_name}_Final_2026_2027_BPI_plot.png")

print("\n✅ All 5 BPI plots saved to:", forecast_dir_uf)

"""# Final Final 2026 Forecasts BS PI end"""